In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

##Tokenrizer

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

text="댓글은 인터넷 게시물 밑에 남길 수 있는 짧은 글이다."
list_text=[["댓글은 인터넷 게시물 밑에 남길 수 있는 짧은 글이다."], ['선한 영향력 굿.']]

tokenizer = Tokenizer()

tokenizer.fit_on_texts([text])
# tokenizer.fit_on_texts(list_text)

tokenizer.word_index

{'게시물': 3,
 '글이다': 9,
 '남길': 5,
 '댓글은': 1,
 '밑에': 4,
 '수': 6,
 '인터넷': 2,
 '있는': 7,
 '짧은': 8}

In [3]:
sub_text="유즈넷(USENET) 뉴스그룹 초창기 시절 'reply'를 '리플라이', '답장' 등으로 주로 사용하였다"
encoded=tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

[]


In [4]:
sub_text="보통 인터넷 게시물 밑에는 댓글란이 있어 그 게시물과 관련하여 독자는 의견을 표할 수 있다"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 3, 6]


In [5]:
one_hot = tf.keras.utils.to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


##interger Encoding

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer
sentences=[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]
tokenizer = Tokenizer(num_words = 5 + 1, oov_token='OOV')
# 빈도수 상위 5개 단어만 사용. 숫자 0과 OOV를 고려해서 단어 집합의 크기는 +2
tokenizer.fit_on_texts(sentences)
print(tokenizer.word_index)

{'OOV': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'kept': 5, 'person': 6, 'word': 7, 'keeping': 8, 'good': 9, 'knew': 10, 'driving': 11, 'crazy': 12, 'went': 13, 'mountain': 14}


In [7]:
# print('단어 OOV의 인덱스 : {}'.format(tokenizer.word_index['OOV']))

In [8]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [9]:
print(tokenizer.texts_to_sequences(sentences))

[[2, 1], [2, 1, 1], [2, 4, 1], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


##Korea Tokenizer

In [10]:
!pip install konlpy

KeyboardInterrupt: ignored

###word

In [ ]:
from konlpy.tag import Okt  
okt=Okt()  
token=okt.morphs("나는 자연어 처리를 배운다")  
print(token)

In [ ]:
type(token)

In [ ]:
!pip install nltk

In [ ]:
import nltk
nltk.download('punkt')

In [ ]:
from nltk.tokenize import word_tokenize  
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop.")) 

In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
print(text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

In [ ]:
from nltk.tokenize import word_tokenize
text="열심히 코딩한 당신, 연휴에는 여행을 가봐요."
from nltk.tag import pos_tag
x=word_tokenize(text)
pos_tag(x)

In [ ]:
!pip install konlpy

In [ ]:
from konlpy.tag import Okt  
okt=Okt()  
print(okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print(okt.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))  
print(okt.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))  

###sentance

In [ ]:
from nltk.tokenize import sent_tokenize
text="His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to mae sure no one was near."
print(sent_tokenize(text))

In [ ]:
from nltk.tokenize import sent_tokenize
text="I am actively looking for Ph.D. students. and you are a Ph.D student."
print(sent_tokenize(text))

###표제어와 어간 추출

In [ ]:
from nltk.stem import PorterStemmer
s=PorterStemmer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
# words=['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']  
print([s.stem(w) for w in words])


##one hot

In [ ]:
# tf.keras.preprocessing.text.one_hot(
#     text, n, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' '
# )

##Embedding

In [ ]:
imdb = keras.datasets.imdb

In [ ]:
# 단어와 정수 인덱스를 매핑한 딕셔너리
word_index = imdb.get_word_index()
# word_index
# word_index['movie']
# # 처음 몇 개 인덱스는 사전에 정의되어 있습니다
# word_index = {k:(v+3) for k,v in word_index.items()}
# word_index["<PAD>"] = 0
# word_index["<START>"] = 1
# word_index["<UNK>"] = 2  # unknown
# word_index["<UNUSED>"] = 3


In [ ]:
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

def decode_review(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

# index_to_word = {word_index[k]: k for k in word_index}
# for w in x_train[0] :
#   print(word_index[w], end=', ')

In [ ]:
(x_train_all, y_train), (x_test_all, y_test) = imdb.load_data(num_words=100)  #num_words=10000

In [ ]:
type(x_train_all), x_train_all.shape, x_train_all

In [ ]:
decode_review(x_train_all[0])   

In [ ]:
(x_train_all, y_train), (x_test_all, y_test) = imdb.load_data(num_words=10)  #num_words=10000

In [ ]:
type(x_train_all), x_train_all.shape, x_train_all

In [ ]:
decode_review(x_train_all[0])   

In [ ]:
(x_train_all, y_train), (x_test_all, y_test) = imdb.load_data(num_words=1000, skip_top=20)  #num_words=10000

for i in range(len(x_train_all)):
  x_train_all[i] = [w for w in x_train_all[i] if w > 2]

In [ ]:
type(x_train_all), x_train_all.shape, x_train_all

In [ ]:
decode_review(x_train_all[0])  

In [ ]:
len(x_train_all[0])

In [ ]:
len(x_train_all[3]), len(x_train_all[5])

In [ ]:
# x_train = keras.preprocessing.sequence.pad_sequences(y_train_all,
#                                                         value=word_index["<PAD>"],
#                                                         padding='post',
#                                                         maxlen=256)
pad_len = 100
x_train = keras.preprocessing.sequence.pad_sequences(x_train_all, maxlen=pad_len)

x_test = keras.preprocessing.sequence.pad_sequences(x_test_all, maxlen=pad_len)

###stopword

In [11]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import word_tokenize 
from nltk.corpus import stopwords  

print(stopwords.words('english')[:10], stopwords.words('spanish')[:10])
example = "Family is not an important thing. It's everything."
stop_words = stopwords.words('english')
example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = ['아무렇게나', '다', '게', '예컨대']
word_tokens = word_tokenize(example);	result = [];
for w in word_tokens: 
    if w not in stop_words: 
        result.append(w) 
print(word_tokens); 		print(result);

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"] ['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se']
['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']
['고기를', '구우려고', '하면', '안', '돼', '.', '고기라고', '같은', '아니거든', '.', '삼겹살을', '구울', '때는', '중요한', '있지', '.']


In [ ]:
print(stopwords.words('spanish')[:10]  )

['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se']


In [ ]:
' '.join(['a','b','c'])

'a b c'

##Embadding

In [ ]:
import tensorflow as tf
import numpy as np

model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=1000, output_dim=1)) #,input_length=10))
# dimension.  
input_array = np.random.randint(1000, size=(32, 10))
print(input_array.shape, input_array, )
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
print(output_array.shape, output_array)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
text="나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"
tok = Tokenizer();	tok.fit_on_texts([text])
print(tok.word_index)


{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=10, output_dim=2)) #,input_length=10))
# dimension.  
input_array = '나랑 점심 먹으러 갈래 점심 메뉴는'
encoded=tok.texts_to_sequences([input_array])[0]
print(len(encoded), encoded, )

6 [4, 2, 5, 1, 2, 6]


In [ ]:
model.input, type(encoded)

(<tf.Tensor 'embedding_13_input:0' shape=(None, None) dtype=float32>, list)

In [ ]:
model.compile('rmsprop', 'mse')
# output_array = model.predict(tf.expand_dims(encoded, 0))
output_array = model.predict([encoded])
print(output_array.shape, output_array)

(1, 6, 2) [[[ 0.03117298  0.00447661]
  [-0.03642578  0.01174479]
  [-0.01825685 -0.03935102]
  [ 0.03170705 -0.03034216]
  [-0.03642578  0.01174479]
  [-0.04880217 -0.0336172 ]]]


In [ ]:
tf.expand_dims(encoded, 0)

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[2, 5, 1, 6, 3, 7]], dtype=int32)>

###Seman

In [ ]:
pip install sentencepiece

     |████████████████████████████████| 1.1MB 5.5MB/s 


In [ ]:
import sentencepiece as spm
spm.SentencePieceTrainer.Train('--input=test/test.txt --model_prefix=m --vocab_size=400')

In [ ]:
sp = spm.SentencePieceProcessor()
sp.Load("m.model")

True

In [ ]:
print(sp.EncodeAsPieces("유해 봉환을 위해 최신예 공중급유기인 시그너스(KC-330)가 미국 하와이로 갔다."))

NameError: ignored

In [ ]:
print(sp.EncodeAsIds("유해 봉환을 위해 최신예 공중급유기인 시그너스(KC-330)가 미국 하와이로 갔다."))

NameError: ignored

In [ ]:
sp.DecodeIds([65, 3, 291, 344, 6, 98, 25, 3, 330, 5])

'유해 봉환을 위해 최.'

In [ ]:
sp.GetPieceSize()

400

In [ ]:
sp.IdToPiece(2)

'</s>'

In [ ]:
sp.PieceToId('')

0