# Backpropagation

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
def sigmoid(x):
  return 1 / (1+np.exp(-x))

def sigmoid_prime(x):
  return x * (1-x)

In [0]:
input1 = np.array([np.arange(4), np.arange(4)])
input1

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [0]:
# 4 x 3 x 2
n_records, n_inputs = input1.shape
n_records, n_inputs

(2, 4)

In [0]:
n_hidden = 3
weights_input_to_hidden = np.random.normal(0, n_inputs**-5, size=(n_inputs, n_hidden))
weights_input_to_hidden

array([[ 7.23417559e-04,  7.42568179e-04,  2.56779888e-04],
       [-4.50080858e-04,  1.84989861e-05,  5.36220034e-04],
       [-9.40663462e-04, -4.10040146e-05,  1.57996635e-03],
       [ 2.30260943e-03, -4.31313547e-04,  4.45620163e-05]])

In [0]:
n_output = 2
weights_input_to_output = np.random.normal(0, n_inputs**-5, size=(n_hidden, n_output))
weights_input_to_output

array([[-0.00014459,  0.00040281],
       [ 0.00036645, -0.00052825],
       [-0.00111902,  0.00043212]])

In [0]:
hidden1 = sigmoid(np.dot(input1, weights_input_to_hidden))
hidden1_output = sigmoid(np.dot(hidden1, weights_input_to_output))
hidden1_output

array([[0.49988752, 0.5000386 ],
       [0.49988752, 0.5000386 ]])

# backpropagation

In [0]:
input2 = np.array([0.1, 0.3])

In [0]:
predict = 1

In [0]:
weights = np.array([0.4, -0.2])

In [0]:
hidden_weight = 0.1

In [0]:
hidden_output = sigmoid(np.dot(input2, weights))

In [0]:
output = sigmoid(np.dot(hidden_output, hidden_weight))
output

0.512372477962617

In [0]:
error = predict - output

In [0]:
err_term = error * sigmoid_prime(output)
err_term

0.1218322353606694

In [0]:
hidden_err_term = hidden_weight * err_term * sigmoid_prime(output)
hidden_err_term

0.0030439408979544076

In [0]:
learning_rate = 0.5

In [0]:
delta_w = learning_rate * err_term * hidden_output
delta_w_hidden = learning_rate * hidden_err_term * input2
delta_w, delta_w_hidden

(0.030153488404045865, array([0.0001522 , 0.00045659]))